* dired-nnn

This emacs package implements nnn-like (github.com/jarun/nnn) file
select/move/paste, inspired by dired-ranger of dired-hacks.

** Usage

Functions:

- ~dired-nnn-toggle-mark~ toggles marking of the file at the point.
- ~dired-nnn-paste~ pastes marked files from all dired buffers into the
  ~dired-current-directory~ using ~dired-copy-file~.
- ~dired-nnn-move~ moves marked files from all dired buffers into the
  ~dired-current-directory~ using ~dired-rename-file~.

Customization:

- ~dired-nnn-mark-new-files~ (default: nil) control whether newly moved or
  pasted files are marked for further actions.

nnn equivalence:

| nnn key | nnn action | dired equivalent                   |
|---------+------------+------------------------------------|
| SPC     | Toggle sel | dired-nnn-toggle-mark              |
| a       | Sel all    | dired-mark-subdir-files (built-in) |
| A       | Invert sel | dired-toggle-marks (built-in)      |
| p       | Paste sel  | dired-nnn-paste                    |
| v       | Move sel   | dired-nnn-move                     |

** ~doom-modeline~ segment

Display the number of marked files in the modeline; mouse over to see their
names.

#+begin_src elisp
(doom-modeline-def-segment dired-nnn
  (let ((marked-files (dired-nnn--marked-files)))
    (when (and (derived-mode-p 'dired-mode) (length> marked-files 0))
      (propertize
       (concat
        (doom-modeline-spc)
        (format "+%d" (length marked-files))
        (doom-modeline-spc))
       'face 'doom-modeline-highlight
       'help-echo (concat
                   "dired-nnn marked files:\n"
                   (mapconcat
                    (lambda (file)
                      (format "  %s" file))
                    marked-files "\n"))
       'mouse-face 'doom-modeline-highlight))))
#+end_src
